# Generated by Django 4.2 on 2023-04-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadCartonEventType',
            fields=[
                ('description', models.CharField(db_column='description', max_length=255)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Load Carton Event Type',
                'verbose_name_plural': 'Load Carton Event Type',
                'db_table': 'load_carton_event_type',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('code', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT')),
                ('addr_line_1', models.CharField(max_length=40)),
                ('addr_line_2', models.CharField(blank=True, max_length=30, null=True)),
                ('locality', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouse',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LoadCartonEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_nbr', models.CharField(max_length=20)),
                ('load_nbr', models.CharField(max_length=20)),
                ('old_stat_code', models.IntegerField()),
                ('new_stat_code', models.IntegerField()),
                ('login_user_id', models.CharField(max_length=15)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion')),
                ('load_carton_event_type', models.ForeignKey(db_column='load_carton_event_type', on_delete=django.db.models.deletion.RESTRICT, to='cartonevents.loadcartoneventtype')),
                ('whse_code', models.ForeignKey(db_column='whse_code', on_delete=django.db.models.deletion.RESTRICT, to='cartonevents.warehouse')),
            ],
            options={
                'verbose_name': 'Load Carton Event',
                'verbose_name_plural': 'Load Carton Events',
                'db_table': 'load_carton_events',
                'ordering': ['creation_date'],
            },
        ),
    ]
