# Generated by Django 4.2 on 2023-04-28 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartonevents', '0002_alter_loadcartonevents_load_carton_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadcartonevents',
            name='load_carton_event_type',
            field=models.ForeignKey(db_column='load_carton_event_type', on_delete=django.db.models.deletion.RESTRICT, to='cartonevents.loadcartoneventtype'),
        ),
    ]
