# Generated by Django 4.1.2 on 2022-11-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name_plural': 'Encargos'},
        ),
    ]
