# Generated by Django 4.1.2 on 2022-11-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_shipment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletjackmaster',
            name='pallet_jack_brcd',
            field=models.CharField(default='?', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PalletJackMasterDtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('mod_date_time', models.DateTimeField(auto_now=True)),
                ('pallet_jack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.palletjackmaster')),
            ],
            options={
                'verbose_name_plural': 'Encargos de Traspaletas',
                'db_table': 'pallet_jack_master_dtl',
            },
        ),
    ]
