# Generated by Django 4.1.2 on 2023-01-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_palletjackmaster_status_palletjackmasterdtl_shipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('description', models.CharField(db_column='description', max_length=255)),
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Type',
                'db_table': 'location_type',
            },
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='putaway_location',
            new_name='current_location',
        ),
        migrations.AddField(
            model_name='shipment',
            name='classified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='classified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_type', to='base.locationtype'),
        ),
    ]
