# Generated by Django 4.1.2 on 2023-01-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_locationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_shipments_current_location', to='base.location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pallet_jack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_shipments_pallet_jack', to='base.palletjackmaster'),
        ),
    ]
