# Generated by Django 4.1.2 on 2023-01-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_shipment_final_desatch_ramp_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palletjackmaster',
            options={'ordering': ['pallet_jack_id'], 'verbose_name_plural': 'Transpaletas'},
        ),
        migrations.AlterModelOptions(
            name='palletjackmasterdtl',
            options={'verbose_name_plural': 'Encargos de Transpaletas'},
        ),
        migrations.AddField(
            model_name='shipment',
            name='colour_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='colour_code_desc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
