# Generated by Django 4.1.2 on 2023-01-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_palletjackmaster_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='final_desatch_ramp_location',
        ),
        migrations.AddField(
            model_name='shipment',
            name='final_despatch_ramp_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_shipments_final_despatch_ramp_location', to='base.location'),
        ),
    ]
